- type: replace
  path: /releases?/name=bpm?
  value:
    name: bpm
    version: 1.1.12
    url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.12
    sha1: 502e9446fa34accaf122ad2b28b6ffa543d5bbca
