- type: replace
  path: /releases?/name=haproxy?
  value:
    name: haproxy
    version: 11.1.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/haproxy-boshrelease?v=11.1.0
    sha1: 3f17e5ae40398536136ab3d59fff5a3cd7f7f294
