- type: replace
  path: /releases?/name=haproxy?
  value:
    name: haproxy
    version: 11.10.1
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/haproxy-boshrelease?v=11.10.1
    sha1: 3977888a5b0fdcccf8f30a64165dcc7b1cec67ca
