releases:
- name: locker
  version: 0.2.1
  url: https://github.com/cloudfoundry-community/locker-boshrelease/releases/download/v0.2.1/locker-0.2.1.tgz
  sha1: ccfcc48d63555a3733c3594d9429a5c1875a9dd2
