---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: starkandwayne/concourse-go
    tag: '1.16' 

inputs:
- name: git
- name: git-ci
- name: bosh-release

outputs:
- name: git

run:
  path: git-ci/ci/scripts/update-release

params:
  RELEASE_NAME:
  RELEASE_PATH:
  BRANCH:
