---
kit:
  name:    dev
  version: latest
  features:
    - small-footprint
    - no-tls
    - prometheus

genesis:
  env:         small-footprint-prometheus

params:
  external_domain: concourse.testing.examle
