---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse-go

inputs:
- name: git
  # path: concourse-genesis-kit
- name: git-ci

run:
  path: git-ci/ci/tasks/spec-tests/task