---
meta:
  vault: (( concat "secret/" params.vault ))
  default:
    azs: [z1, z2, z3]
    no_proxy: [localhost, 127.0.0.1]

params:
  concourse_network: concourse
  concourse_vm_type: small
  concourse_disk_type: concourse

  stemcell_os: ubuntu-trusty
  stemcell_version: latest

  volume_driver: detect

update:
  canaries: 1
  max_in_flight: 4
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  serial: false

instance_groups:
  - name: worker
    instances: (( grab params.workers ))
    azs: (( grab params.availability_zones || meta.default.azs ))
    stemcell: default
    vm_type: (( grab params.worker_vm_type || "concourse-worker" ))
    networks:
    - name: (( grab params.concourse_network ))
    update:
      serial: true
      max_in_flight: (( grab instance_groups.worker.instances ))
    jobs:
      - release: concourse
        name: worker
        properties:
          http_proxy_url:  (( grab params.http_proxy  || "" ))
          https_proxy_url: (( grab params.https_proxy || "" ))
          no_proxy:        (( grab params.no_proxy    || meta.default.no_proxy ))
          tsa:
            worker_key:
              private_key: (( vault meta.vault "/tsa/worker_key:private" ))
              public_key: (( vault meta.vault "/tsa/worker_key:public" ))
          baggageclaim:
            forward_address: 127.0.0.1:7788
          gargen:
            forward_address: 127.0.0.1:7777
      - release: concourse
        name: baggageclaim
        properties:
          driver: (( grab params.volume_driver ))
      - release: garden-runc
        name: garden
        properties:
          garden:
            listen_network: tcp
            listen_address: 0.0.0.0:7777

releases:
- name: concourse
  sha1: aaa4e4d42adb2293abc79422351ca71ed548f95c
  url: https://bosh.io/d/github.com/concourse/concourse?v=3.13.0
  version: 3.13.0
- name: garden-runc
  sha1: 54cbb89cae1be0708aa056185671665d7f4b2a4f
  url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=1.13.1
  version: 1.13.1
- name: slack-notification-resource
  sha1: a64c65d1f23ea089746e698f29dbe522dd716c1b
  url: https://bosh.io/d/github.com/cloudfoundry-community/slack-notification-resource-boshrelease?v=9
  version: 9

stemcells:
- alias: default
  os: (( grab params.stemcell_os ))
  version: (( grab params.stemcell_version ))
