---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse

inputs:
- name: git
- name: git-ci
- name: git-latest-tag

outputs:
  - name: release-notes

run:
  path: git-ci/ci/tasks/generate-release-notes/task