---
meta:
  jobs:
    haproxy:
      properties:
        ha_proxy:
          tcp:
            - name: web_https
              port: 443
              backend_port:    443
              backend_servers:  (( grab instance_groups.web.networks.0.static_ips || instance_groups.concourse.networks.0.static_ips ))
    web:
      properties:
        tls:
          bind_port: 443
          cert:
            certificate:      (( vault meta.vault "/ssl/server:certificate" ))
            private_key:       (( vault meta.vault "/ssl/server:key" ))
