---
meta:
  jobs:
    haproxy:
      properties:
        ha_proxy:
          tcp:
            - name: web_https
              port: 443
              backend_port:    443
              backend_servers:  (( grab instance_groups.web.networks.0.static_ips || instance_groups.concourse.networks.0.static_ips ))
    atc:
      properties:
        tls_bind_port: 443
        tls_cert:      (( vault meta.vault "/ssl/server:certificate" ))
        tls_key:       (( vault meta.vault "/ssl/server:key" ))
