#!/bin/bash
echo "$GENESIS_REQUESTED_FEATURES"

if want_feature "ocfp" ; then
  true # Contract handles database (via vault) & sizing (dev/prod)
else # non-ocfp based 
  if ! want_feature "external-db" ; then
    echo "+internal-db"
  fi
  if want_feature "full" || want_feature "small-footprint"  ; then
    echo "+locker"
  fi
fi
