#!/bin/bash
set -eu

if [[ $GENESIS_DEPLOY_RC == 0 ]]; then

  mode="Full"
  want_feature workers && mode="Satellite (workers only)"

  describe "" "$(cat <<EOF

#M{$GENESIS_ENVIRONMENT} $mode Concourse deployed!

For details about the deployment, run

  #G{$GENESIS_CALL info $GENESIS_ENVIRONMENT}

To download the '#C{fly}' CLI for the first time, run

  #G{$GENESIS_CALL do $GENESIS_ENVIRONMENT -- download-fly /location/in/your/path}

To update your current version of the '#C{fly}' CLI, run

  #G{$GENESIS_CALL do $GENESIS_ENVIRONMENT -- download-fly --sync}

To target & log into this Concourse with fly, run

  #G{$GENESIS_CALL do $GENESIS_ENVIRONMENT -- login}

To run a fly command against this Concourse, run (without -t <target>)

  #G{$GENESIS_CALL do $GENESIS_ENVIRONMENT -- fly [options and arguments]}

  As an extra efficiency, if you run the '#C{fly}' addon above, it will
  automatically create the target if one doesn't exist, and log you in if
  you're not already logged in, before running your desired command.

Finally, to visit the Concourse Web Portal, run:

  #G{$GENESIS_CALL do $GENESIS_ENVIRONMENT -- visit}
EOF
  )" ""
fi
