---
meta:
  ocfp:
    certs:
      trusted:
        - (( vault genesis.secrets_mount "certs/org:ca" )) # Organization CA, if exists
        - (( vault genesis.secrets_mount "certs/dbs:ca" )) # External Databases CA

# AWS-specific OCFP integrations

# Web VM integration with AWS IaaS
instance_groups:
- name: web
  vm_extensions: (( append [ "concourse-lb" ] ))
- name: worker
  azs:
  - (( replace ))
  - (( grab params.availability_zones[1] ))
  - (( grab params.availability_zones[2] ))
