---
meta:
  concourse_db:
    username:    (( grab params.external_db_user || "atc" ))
    password:    (( vault meta.vault "/database/external:password" ))
    hostname:    (( param "Please provide the hostname of the external database server" ))
    port:        (( grab params.external_db_port || 5432 ))
    database:    (( grab params.external_db_name || "atc" ))
    sslmode:     (( grab params.external_db_sslmode || "verify-ca" ))

---
- type: remove
  path: /meta/jobs/postgres

- type: remove
  path: /instance_groups/name=db?

- type: replace
  path: /instance_groups/name=web?/jobs/-
  value:
    name: locker
    .:    (( inject meta.jobs.locker ))

- type: replace
  path: /params/external_db_host?
  value: (( grab meta.concourse_db.hostname ))

- type: replace
  path: /meta/jobs/web/properties/postgresql
  value:
    database:   (( grab meta.concourse_db.database ))
    host:       (( grab meta.concourse_db.hostname ))
    port:       (( grab meta.concourse_db.port ))
    role:
      name:     (( grab meta.concourse_db.username ))
      password: (( grab meta.concourse_db.password ))
    sslmode:    (( grab meta.concourse_db.sslmode ))

- type: remove
  path: /releases/name=postgres

- type: remove
  path: /instance_groups/name=concourse?/jobs/name=postgres