---
meta:
  concourse_db:
    ca: (( param "Please specify the CA certificate for the external DB" ))

---
- type: replace
  path: /params/external_db_ca?
  value: (( grab meta.concourse_db.ca ))

- type: replace
  path: /meta/jobs/web/properties/postgresql/ca_cert?
  value:
    certificate: (( grab meta.concourse_db.ca ))
