---
meta:
  concourse_okta_name:   (( vault meta.vault "/okta:display_name" ))
  main_team_saml_groups: (( vault meta.vault "/okta:main_team_saml_groups" ))

---
instance_groups:
  - name: web
    jobs:
      - name: web
        properties:
          main_team:
            auth:
              saml:
                groups:
                  - (( grab meta.main_team_saml_groups ))

          saml_auth:
            display_name: (( grab meta.concourse_okta_name || "Okta" ))
            sso_issuer:   (( vault meta.vault "/okta:sso_issuer" ))
            sso_url:      (( vault meta.vault "/okta:sso_url" ))
            ca_cert:
              certificate:  (( vault meta.vault "/okta:ca_cert" ))

