---
meta:
  concourse_okta_name: (( vault meta.vault "/okta:name" ))

---
instance_groups:
  - name: web
    jobs:
      - name: web
        properties:
          saml_auth:
            display_name: (( grab meta.concourse_okta_name || "Okta" ))
            ca_cert:
              sso_url:     (( vault meta.vault "/okta:sso_url" ))
              #certificate: (( vault meta.vault "/okta:ca_cert" )) It's a SaaS, public cert trust should just work.
