meta:
  metrics:
    prometheus:
      port: (( grab params.prometheus_metrics_port || 9391 ))

instance_groups:
- name: haproxy
  jobs:
  - name: haproxy
    properties:
      ha_proxy:
        tcp:
        - name: metrics_http
          port: (( grab meta.metrics.prometheus.port ))
          backend_port: (( grab meta.metrics.prometheus.port ))
          backend_servers: (( grab instance_groups.concourse.networks.0.static_ips ))
- name: concourse
  jobs:
  - name: web
    properties:
      prometheus:
        bind_ip: 0.0.0.0
        bind_port: (( grab meta.metrics.prometheus.port ))

