params:
  # we provide a dumb no-op for rules
  shout_rules: |
    ((for *
       (when *
         (remind 24 hours))))

exodus:
  shout_url:            (( concat "http://" instance_groups.web.networks[0].static_ips[0] ":7109" ))
  shout_admin_username: admin
  shout_admin_password: (( vault meta.vault "/shout/admin:password" ))
  shout_ops_username:   ops
  shout_ops_password:   (( vault meta.vault "/shout/ops:password" ))

instance_groups:
  - name: web
    jobs:
      - name:    shout
        release: shout
        properties:
          ops:
            username: ops
            password: (( vault meta.vault "/shout/ops:password" ))
          admin:
            username: admin
            password: (( vault meta.vault "/shout/admin:password" ))
          rules: (( grab params.shout_rules ))

releases:
  - name:   shout
    version: 0.1.0
    sha1:    73c5c0161730a655c03f5a6ceb1c8b2e33403874
    url:     https://github.com/jhunt/shout-boshrelease/releases/download/v0.1.0/shout-0.1.0.tar.gz
