params:
  # we provide a dumb no-op for rules
  shout_rules: |
    ((for *
       (when *
         (remind 24 hours))))


meta:
  vm_ip: (( grab instance_groups.web.networks[0].static_ips[0] || instance_groups.concourse.networks[0].static_ips[0] ))

exodus:
  shout_url:            (( concat "http://" meta.vm_ip ":7109" ))
  shout_admin_username: admin
  shout_admin_password: (( vault meta.vault "/shout/admin:password" ))
  shout_ops_username:   ops
  shout_ops_password:   (( vault meta.vault "/shout/ops:password" ))

instance_groups:
  - name: web
    jobs:
      - name:    shout
        release: shout
        properties:
          ops:
            username: ops
            password: (( vault meta.vault "/shout/ops:password" ))
          admin:
            username: admin
            password: (( vault meta.vault "/shout/admin:password" ))
          rules: (( grab params.shout_rules ))

releases:
- (( append ))
- (( grab meta.releases.shout))