---
params:
  vault_token:             ~
  vault_auth_backend:      approle
  vault_approle_role_id:   (( vault meta.vault "/approle/concourse:approle-id" ))
  vault_approle_secret_id: (( vault meta.vault "/approle/concourse:approle-secret" ))

---
meta:
  concourse_vault:
    token:             ~
    auth_backend:      (( grab params.vault_auth_backend ))
    approle_role_id:   (( grab params.vault_approle_role_id ))
    approle_secret_id: (( grab params.vault_approle_secret_id ))

---
meta:
  jobs:
    web:
      properties:
        vault:
          auth:
            client_token: (( prune ))
            backend:      (( grab meta.concourse_vault.auth_backend ))
            params:
              role_id:   (( grab meta.concourse_vault.approle_role_id ))
              secret_id: (( grab meta.concourse_vault.approle_secret_id ))


