---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse-go
    tag: '1.14' 

inputs:
- name: git
- name: git-ci
- name: bosh-release

outputs:
- name: pushme

run:
  path: git-ci/ci/tasks/update-bosh-release/task

params:
  OPS_FILE_PATH:
  RELEASE_NAME:
  BRANCH:
